server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: xiyuan.link:8848
dubbo:
  scan:
    base-packages: com.xiyuan.project
  registry:
    address: nacos://xiyuan.link:8848
