server:
  port: 8082
spring:
  application:
    name: api-gateway
  redis:
    host: xiyuan.link
    password: Sql123..
    port: 6379
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: xiyuan.link:8848
dubbo:
  scan:
    base-packages: com.xiyuan.apicommon
  registry:
    address: nacos://xiyuan.link:8848

logging:
  level:
    org.springframework.cloud.gateway: trace

