server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: api-backend
#  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xiyuan.link:3306/api_platform
    username: root
    password: Sql123..
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 0
    host: xiyuan.link
    port: 6379
    timeout: 5000
    password: Sql123..
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  cloud:
    # nacos注册中心配置
    nacos:
      discovery:
        server-addr: xiyuan.link:8848
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://xiyuan.link:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)