server:
  port: 8092
  servlet:
    context-path: /
spring:
  application:
    name: api-interface
  cloud:
    nacos:
      discovery:
        server-addr: zeekr.live:8848
        namespace: 531135f1-4e25-4e41-b4b5-722580517de7
